### ISSUE TITLE
Limit max length of numInputs

### ISSUE THREAD

**Issue by ajayns** [devfolioco/react-otp-input#1]
Current plan is to restrict it to 10

**Comment by ojaswa1942** [comment]
Do you also plan to enforce a minimum number of numInputs?

**Comment by ajayns** [comment]
@ojaswa1942 Hey! As of now, we haven't exactly planned what the limits should be. So it would be great if you could share the logic behind setting a particular limit as well. :)

**Comment by ojaswa1942** [comment]
Presently we can also pass 0 and negative values to numInputs and that results in a no input fields at all.. It'd be good if a minimum default is rendered for invalid values of numInputs. The same can be done for high values of numInputs and a default maximum number, say 10 can be used instead

![Screenshot for numInputs = 0](https://user-images.githubusercontent.com/35270649/66147361-53c6d580-e62c-11e9-8078-ed858889957e.png)

![Screenshot for numInputs = 178](https://user-images.githubusercontent.com/35270649/66147489-94265380-e62c-11e9-95f8-93ab7b9ae82a.png)

**Comment by nikhilgupta30** [comment]
this pull request restricts the length of numInput
https://github.com/devfolioco/react-otp-input/pull/66
@ajayns
