### ISSUE TITLE
Changing from uncontrolled input to controlled

### ISSUE THREAD

**Issue by kunalmhatre** [devfolioco/react-otp-input#10]
Hey, nice work - really appreciate it. Currently, I am using React - React-DOM 16.6.0 and after I enter the first digit, following **warning** is shown in the console.

_A component is changing an uncontrolled input of type tel to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component._

**Additional Info:** I rendered the **OtpInput** component in React.Component. Following is the screenshot of the warning.

![screenshot 2019-01-19 at 5 55 36 pm](https://user-images.githubusercontent.com/20396596/51426655-ae8ddd80-1c13-11e9-846e-12763abf75b0.png)

Thanks for the help. :)

**Comment by kunalmhatre** [comment]
Hi again, here is something that can help: https://stackoverflow.com/questions/37427508/react-changing-an-uncontrolled-input

**Comment by ajayns** [comment]
Thank you for the feedback and noticing this, I will certainly look into it.

**Comment by kunalmhatre** [comment]
Hey, thanks a lot for the fix. 👍

**Comment by ajayns** [comment]
You're welcome. Thanks for opening the issue! :)
