### ISSUE TITLE
When we click on the backspace button, the cursor is going back to the previous element, but it should stay in the current element position only.

### ISSUE THREAD

**Issue by srikanthpathlavath** [devfolioco/react-otp-input#100]
When we click on the backspace button, the cursor is going back to the previous element, but it should stay in the current element position only. how to achieve this ?
- **Steps to reproduce the issue**:

- **Relevant error messages and/or screenshots**:

**Comment by ankiiitraj** [comment]
Like to work on it!

**Comment by adithyaakrishna** [comment]
Hi @apollonian , Can I work on this issue?

**Comment by agarwalBinay18** [comment]
can I work on this issue?

**Comment by sandeepkambham08** [comment]
This should be the behavior when the user hits on backspace to edit a single number in the input.
