### ISSUE TITLE
Is this repo not being maintained anymore?

### ISSUE THREAD

**Issue by basantmatharu** [devfolioco/react-otp-input#104]
I see that the last commit was in November 2019 and there are so many open pull requests.
I'm wondering if it's a good idea to invest in this repo or just write my own OTP component.

**Comment by apollonian** [comment]
@basantmatharu I'm going through the current issues and planning to resolve most of the core ones. Releasing an update tomorrow! Check out the alpha on https://roi2.surge.sh

**Comment by apollonian** [comment]
Just released an [upgrade](https://github.com/devfolioco/react-otp-input/releases/tag/v2.0.0)! (And, therefore closing the issue). Do give a check. :v:
