### ISSUE TITLE
Otp Input is not Showing

### ISSUE THREAD

**Issue by TheSayantan96** [devfolioco/react-otp-input#110]
- **Describe the Feature Request**
When I am typing inside the OTP inputs nothing is showing even after the inputStyle color set to black
- **Describe Preferred Solution**

**Comment by apollonian** [comment]
Hey @TheSayantan96

Could you please add some information (e.g. browser / device info. / screen recording / additional logs you're getting in the console) to the issue so that I can try to reproduce this? A CodeSandbox link to you implementation would be helpful too. Thanks.

**Comment by Superitum** [comment]
Hi @apollonian I'm experiencing the same issue. I installed react-otp-input and used some of the samples to test. When a number or other charater is entered the cursor moves to the next input but nothing is displayed.
Dev environment: VS Code

**Comment by apollonian** [comment]
@Superitum Thanks for reporting. I'll recheck on Windows. Are you able to run [the demo](https://devfolioco.github.io/react-otp-input/)?

**Comment by Superitum** [comment]
Demo works fine. Tested code on Win 10 as well, same issue.
Could be the code.. I created a component which is then included in the App

Component code
`import React, { Component } from 'react';
import OtpInput from 'react-otp-input';

class otps extends Component {
    state = {
        otp: '',
      };
     
    handleChange = otp => {
        this.setState({ otp });
    };

    render() { 
        return ( 
            <OtpInput            
                inputStyle={{  
                    width: '3rem',  
                    height: '3rem',  
                    margin: '20px 1rem',  
                    fontSize: '1rem',  
                    borderRadius: 4,  
                    border: '2px solid rgba(0,0,0,0.3)',                      
                }}  
              onChange={this.handleChange}
              numInputs={6}
              separator={<span>-</span>}
            />              
            );
    }
}
 
export default otps;`

App code
`import React from 'react';
import OTP from './components/otpFields';

function App() {
  return ( 
    <div>
      <OTP/>
    </div>              
  );
}

export default App;`

**Comment by Superitum** [comment]
code seems to not display correctly in the comment above. see images.
![image](https://user-images.githubusercontent.com/18702675/89200198-f5ea7d80-d5af-11ea-9750-0c6ce75be51a.png)
![image](https://user-images.githubusercontent.com/18702675/89200270-0a2e7a80-d5b0-11ea-8730-3284f0c2d95c.png)

**Comment by pcphatweb** [comment]
Hey everybody

I have the same problem as @TheSayantan96 
@apollonian Do you think the problem was in the virtual DOM of ReactJS?

**Comment by apollonian** [comment]
@Superitum I don't see the `value` prop being passed to `OtpInput` which is likely causing this issue (`value={top}`). The component no longer works as uncontrolled. Sorry, If the demo code has this error, I'll fix it. cc @pcphatweb

**Comment by Superitum** [comment]
> ```diff
> value={this.state.otp}
> ```

@apollonian Thank you that was the missing piece of the puzzle!

**Comment by apollonian** [comment]
Thanks @Superitum. I've updated the [sample code](https://github.com/devfolioco/react-otp-input#basic-usage) and [CodeSandbox](https://codesandbox.io/s/react-otp-input-demo-v2-1iy52). 

@TheSayantan96 I'm assuming you had the issue because of the erroneous sample code. Please reopen the issue if you think it's 'cause of something else.

**Comment by TheSayantan96** [comment]
@apollonian Can you please give a demo using setState?

**Comment by apollonian** [comment]
@TheSayantan96 `this.setState` can only be called on a class component. `OtpVerifyForm` here is a "functional" component so it does not have a `this.setState` (no `this`, nor a constructor, no render() method unlike the "class" component) which explains the error. 

The second item returned by `useState` (`setOTP`) is a function to update the state value (OTP) itself so we can further pass it along to OtpInput's `onChange` prop, like so: `<OtpInput ... onChange={setOTP} />`

**Comment by NOURELsayed** [comment]
I have the same issue and this solution did not work with me, can you help me please?

**Comment by apollonian** [comment]
@NOURELsayed Could you add a codesandbox repro or show us how your code looks like?

**Comment by NOURELsayed** [comment]
import React, { Component } from "react";
import ReactDOM from "react-dom";
import OtpInput from "react-otp-input";

import "./App.css";

export default class App extends Component {
  state = {
    otp: "",
  };
  render() {
    return (
      <div>
        <OtpInput
          value={this.state.otp}
          onChange={(otp) => console.log(otp)}
          numInputs={6}
          separator={<span>-</span>}
          inputStyle={{
            width: "3rem",
            height: "3rem",
            margin: "20px 1rem",
            fontSize: "2rem",
            borderRadius: 4,
            border: "2px solid rgba(0,0,0,0.3)",
          }}
          placeholder="hh"
        />
      </div>
    );
  }
}

**Comment by apollonian** [comment]
@NOURELsayed the `onChange` here should be updating the otp state. `onChange={(otp) => this.setState({ otp })}`. Take a look at the example here pls! https://github.com/devfolioco/react-otp-input#basic-usage

**Comment by apollonian** [comment]
@NOURELsayed Might be 'cause of the syntax errors. Check this out: https://codesandbox.io/s/otp-test-22vgt

**Comment by nadeghi** [comment]
Add higher width value for inputStyle

**Comment by roguemaps** [comment]
Just in case someone comes across this looking for the simple format with functional components - 

`const App = () => {
  const [otp, setOtp] = useState("");
  return (
    <OtpInput
      value={otp}
      onChange={setOtp}
      numInputs={6}
      separator={<span>-</span>}
      inputStyle="foo"
      isInputNum
    />
  );
};`

**Comment by ashishbakingo** [comment]
Otp is not working on a functional component. As I type inside the box, the value does not get filled in but the cursor keeps moving to the next box. I have also provided the value prop. I don't even see the console.log() that is inside my handleChnage() function.

My code:

import React, { useState } from "react";
import OtpInput from "react-otp-input";

export default function Step3(props) {
  const [otp, setotp] = useState();
  
  const handleChange = (data) => {
    console.log("data", data)
    setotp(data);
  };

  return (
   <OtpInput
        isInputNum={true}
        value={otp}
        onChange={handleChange}
        numInputs={6}
        separator={<span> </span>}
        inputStyle={styles.otpInput}
      />
 )
}

**Comment by Hilton-Borah** [comment]
<OtpInput
  value={otp}
  placeholder="000000"
  onChange={setOtp}
  OTPLength={6}
  otpType="number"
  skipDefaultStyles={true}
  autoFocus
  inputStyle={{
    border: "1px solid #ccc",
    borderRadius: "4px",
    padding: "10px",
    fontSize: "16px",
    // Add any other styles you need
  }}
/>

Help me, I am not able to apply custom CSS here.

**Comment by Bhagvanji009** [comment]
i got this error : 

Server Error
SyntaxError: Cannot use import statement outside a module

This error happened while generating the page. Any console logs will be displayed in the terminal window.

**Comment by immadisetty-jaya-surya** [comment]
<OtpInput numInputs={4} inputStyle={{
                    width: '3rem',  
                    height: '3rem',  
                    margin: '20px 1rem',  
                    fontSize: '1rem',  
                    borderRadius: 4,  
                    border: '2px solid rgba(0,0,0,0.3)',
                }} separator={<span>-</span>} value={code} onChange={handleChange}  />
                
                guys please help me
                
               import { useState } from "react";
import OtpInput from 'react-otp-input'

const Verification = () => {
    const[code,setCode]= useState('')

    const handleChange = (code) =>{
        setCode(code)
    }

    const handleSubmit = (e) =>{
        e.preventDefault();
        // history.push('./login')
    }
  return (
    <div className="flex flex-col  border-solid border-gray-300 border-2 p-4 rounded-3xl w-[586px] h-[400px] mx-[480px] my-6">
        <h1 className="text-2xl font-bold px-[170px] py-[20px]">Verify your email</h1>
        <p className="text-sm font-medium px-32">Enter the 8 digit code you have received on</p>
        <form onSubmit={handleSubmit} className=" py-8">
            <div className=" px-20 py-3">
                <label htmlFor="code">Code</label>
                <OtpInput numInputs={4} inputStyle={{
                    width: '3rem',  
                    height: '3rem',  
                    margin: '20px 1rem',  
                    fontSize: '1rem',  
                    borderRadius: 4,  
                    border: '2px solid rgba(0,0,0,0.3)',
                }} separator={<span>-</span>} value={code} onChange={handleChange}  />
            </div>
            <button type="submit" className=" bg-black text-white w-[356px] h-[50px] rounded-md text-sm px-3 mx-20 my-10">VERIFY</button>
        </form>
    </div>
  )
}

export default Verification


my code is upto otpInput component line is not working if i comment it everything is working....so otpInput component is not woring please anybody help me please.....
