### ISSUE TITLE
Masking input characters

### ISSUE THREAD

**Issue by cloudchallengers** [devfolioco/react-otp-input#115]
- **Describe the Feature Request**

Sometimes users need to enter secret OTP's in financial applications and they don't want them to be revealed to nearby users, so it's a kind of must have feature to be able to mask the input characters. 

- **Describe Preferred Solution**

We can expose an attribute in API called 'secure' with the default value as false, and can make use of this prop to decide using input type (text vs password).

**Comment by freshlySqueezedBananas** [comment]
+1

**Comment by anoopmsivadas** [comment]
I would like to work on this

**Comment by anoopmsivadas** [comment]
@apollonian can you assign me on this

**Comment by apollonian** [comment]
@anoopmsivadas Sure! Could use your help with this.

**Comment by anoopmsivadas** [comment]
Thanks! expect a PR on October 1st. :grinning:

**Comment by Ayush7-BIT** [comment]
Hey! I like to work on this issue..

**Comment by shivanshBTW** [comment]
is the issue closed yet? I would like to work on this

**Comment by K-Kumar-01** [comment]
@apollonian  @cloudchallengers  I woukd like to work on this issue if it is still open

**Comment by apollonian** [comment]
This feature has been shipped with [v2.3.0](https://github.com/devfolioco/react-otp-input/releases/tag/v2.3.0)!
