### ISSUE TITLE
After passing isInputNum props  true still accepting character values e.

### ISSUE THREAD

**Issue by Brahmrshi** [devfolioco/react-otp-input#116]
After passing the isInputNum true still, the input takes the character "e" is entered in the input. 

`<OtpInput
              value={this.state.otp}
              onChange={(e) => {
                this.setState({ otp: e });
              }}
              numInputs={4}
              hasErrored={true}
              separator={<span>-</span>}
              isInputNum={true}
            />`

**Comment by apollonian** [comment]
Hey @Brahmrshi! 

Could you please add some information (e.g. browser / device info. / additional logs you're getting in the console) to the issue so that I can try to reproduce this?

**Comment by Brahmrshi** [comment]
@apollonian 

I am using chrome browser for testing. and  I think I forgot to update the package. After the update package, I am not facing this issue. But the "e" character is still visible in the input filed. Here is the screenshot of that. The code that I am using is  this.
`  <OtpInput
              value={this.state.otp}
              onChange={this.handleChange}
              numInputs={4}
              isInputNum={true}
              separator={<span>-</span>}
            />`
![image](https://user-images.githubusercontent.com/37209128/90727009-3bad8280-e2e0-11ea-9141-460d085e0103.png)

**Comment by apollonian** [comment]
@Brahmrshi I see! That doesn't look right, though. Which OS are you using?

**Comment by Brahmrshi** [comment]
@apollonian  Windows 10 os
