### ISSUE TITLE
Placeholder missing as a props

### ISSUE THREAD

**Issue by NadirBakhsh** [devfolioco/react-otp-input#117]
- **Describe the Feature Request**
I am creating otp Screen in my React Web Application. i want to show 'O' as a placeholder But it's Props is missing
see the image  what i am want

![image](https://user-images.githubusercontent.com/46098938/91630367-57084400-e9ea-11ea-9535-2cb76f86fbfc.png)

 
- **Describe Preferred Solution**
we need to Pass placeholder Props from component where we using

**Comment by aromalanil** [comment]
I would like to work on this issue.
