### ISSUE TITLE
Changing the numInputs doesn't change the OTP

### ISSUE THREAD

**Issue by KaustubhDamania** [devfolioco/react-otp-input#127]
- **Steps to reproduce the issue**:
  - Visit [the website](https://devfolioco.github.io/react-otp-input/)
  - Enter a code of `n` digits
  - Change `numInputs` on left sidebar to a lower value.
  - Click on `Get OTP` button
  - The old OTP would be displayed

- **Relevant error messages and/or screenshots**:

5 digit OTP: 

![image](https://user-images.githubusercontent.com/33577657/94813382-85c47080-0415-11eb-8913-83a3153910e8.png)

Then lower the `numInput` to 3:

![image](https://user-images.githubusercontent.com/33577657/94813449-a2f93f00-0415-11eb-9694-78e7c130b4f5.png)

Then click on `Get OTP` button

![image](https://user-images.githubusercontent.com/33577657/94813522-b906ff80-0415-11eb-8ae1-a3d6fa7f5d16.png)

The old OTP is shown instead of new OTP.

**Comment by KaustubhDamania** [comment]
I'd like to work on this issue.

**Comment by prateek3255** [comment]
This feels a little out of scope right now, since you can control it via props if you want to.
