### ISSUE TITLE
Feature: Automatically submit when all characters are entered

### ISSUE THREAD

**Issue by nirmalhk7** [devfolioco/react-otp-input#131]
- **Describe the Feature Request**
Instead of only providing user the option to enter the entire OTP and then click the "Get OTP" button, why dont we provide the user with an prop like **whenEntered**. "whenEntered" will be false by default, but if user sets it to true, he needn't click the "Get OTP" button on entering the OTP: the callback function is automatically executed.

- **Describe Preferred Solution**
We just need to implement a listener which listens the OTP entered, and when the final character is entered and "whenEntered" is true, the callback function corresponding to "submit" is automatically executed.

Benefits: I've commonly observed this in many sites which have implemented OTP verification, and I think it makes the user experience more slick in general.

**Comment by nirmalhk7** [comment]
I'd love to be working on this issue myself, please let me know if the idea is worthy of merging into this repo. Thanks!

**Comment by mohammadmujib** [comment]
Good Idea

**Comment by apollonian** [comment]
@nirmalhk7 I'm not sure if I get the use case from what you mention. If you wish to know when the OTP/code has been entered, use the `onChange` handler to detect the same. It is left to the devs to process it and trigger anything else.

**Comment by apollonian** [comment]
Please let me know if you need more help on this. 
Closing this issue & the associated PR since it is beyond the scope of the component.
