### ISSUE TITLE
Addition of autofocus prop

### ISSUE THREAD

**Issue by kunalmhatre** [devfolioco/react-otp-input#14]
**Describe the Feature Request**

Hi again, I request you to add autofocus prop to the component, depending on which the autofocus HTML attribute will be set on the first input box.

**Why?**
For better user accessibility after initial render.

**Comment by rimildeyjsr** [comment]
@ajayns @apollonian - Can I work on this?

**Comment by apollonian** [comment]
Yes please @rimildeyjsr! ✌️

**Comment by rimildeyjsr** [comment]
@apollonian @ajayns - Hey I need some help with the issue, I need to add an autofocus prop (according to the issue) to the component, but isn't `shouldAutoFocus` doing the exact thing? If it is, then this issue is redundant.

Am I missing something here? Need some clarification 😅

**Comment by robinmehra95** [comment]
> @apollonian @ajayns - Hey I need some help with the issue, I need to add an autofocus prop (according to the issue) to the component, but isn't `shouldAutoFocus` doing the exact thing? If it is, then this issue is redundant.
> 
> Am I missing something here? Need some clarification 😅

We need functionality to focus on the first element. Let's say we encountered an error and we want to erase the value and focus to the first box of the otp input

**Comment by gagandeepp** [comment]
Is it open,I can work on this

**Comment by CadencePrestissimo** [comment]
if its open ,  i would like to work on it

**Comment by jitinmaher** [comment]
@kunalmhatre @robinmehra95 Can you please check [this pr](https://github.com/devfolioco/react-otp-input/pull/224) for supporting the feature.

**Comment by kunalmhatre** [comment]
Hey @jitinmaher, nice work, the live demo in your PR looks good to me considering the issue mentioned in this comment https://github.com/devfolioco/react-otp-input/issues/14#issuecomment-676439567. Sorry, but since I opened this PR way back in early 2019 as a user of this repository, I would suggest you to check with the contributors of this repository for any feedback on your PR. All the best! :slightly_smiling_face:

**Comment by kunalmhatre** [comment]
Hey @jitinmaher, nice work, the live demo in your PR looks like a good solution to me for the issue mentioned in this comment https://github.com/devfolioco/react-otp-input/issues/14#issuecomment-676439567 - I am not sure though if this is exactly what @robinmehra95 wanted, so I think you should check with them as well. Sorry, but since I opened this PR way back in early 2019 as a user of this repository, I would suggest you to check with the contributors of this repository for any feedback on your PR. All the best! :slightly_smiling_face:

**Comment by jitinmaher** [comment]
Hi @robinmehra95 , is this issue still open?
