### ISSUE TITLE
Error in main code templete

### ISSUE THREAD

**Issue by kprocks86** [devfolioco/react-otp-input#15]
![screen shot 2019-02-22 at 5 53 34 pm](https://user-images.githubusercontent.com/23704560/53242641-58590200-36cb-11e9-8d92-f3c31ad6bbd2.png)

where `separator={<span>-<span>}`
has to be `separator={<span>-</span>}`
just close the span

**Comment by ajayns** [comment]
Thank you! I have noticed the issue and fixed it in the readme.
