### ISSUE TITLE
Convert class components to functional components with hooks

### ISSUE THREAD

**Issue by g-ravity** [devfolioco/react-otp-input#153]
This is more of a refactor, than an issue. I was wondering if there was any plan to move to functional React components with hooks. I noticed that the codebase is currently using class components. Functional components would be easier to read, debug and also come with some performance benefits.

**Comment by apollonian** [comment]
@g-ravity #35 addressees the same issue.

**Comment by prateek3255** [comment]
This has been fixed with v3
