### ISSUE TITLE
Encode the otp

### ISSUE THREAD

**Issue by RitikaAg** [devfolioco/react-otp-input#154]
- **Add an option for encoding the otp**

- **If the user selects this option the user entered otp will be encoded using shift cipher,if during shift cipher encoding of a digit it exceeds 9 , we will do a modulo by 10**

**Comment by Vishruth-S** [comment]
@RitikaAg  I would like to work on this. Which part of the code can I modify?

**Comment by RitikaAg** [comment]
> * **Add an option for encoding the otp**
> * **If the user selects this option the user entered otp will be encoded using shift cipher,if during shift cipher encoding of a digit it exceeds 9 , we will do a modulo by 10**

Please assign this to me

**Comment by RitikaAg** [comment]
> @RitikaAg I would like to work on this. Which part of the code can I modify?

I opened this issue so I can work on it😅

**Comment by apollonian** [comment]
Hey! This issue is beyond the scope of the component. If you wish to perform any operations on the entered values please use the input handlers and modify state accordingly. Let me know if you need help with this!
