### ISSUE TITLE
Incorrect scripts in README.md

### ISSUE THREAD

**Issue by ShubhankarKG** [devfolioco/react-otp-input#162]
Hi there, been using this Component for some time now! Awesome work!

There aren't necessary steps here. I suppose the commands were changed but the README wasn't updated.

![Screenshot from 2020-10-02 15-29-53](https://user-images.githubusercontent.com/50791000/94911994-9e3f9400-04c4-11eb-8ecc-a43f13f373c6.png)

![Screenshot from 2020-10-02 15-30-17](https://user-images.githubusercontent.com/50791000/94911988-9c75d080-04c4-11eb-8308-4a026792eccd.png)

**Comment by saptarshibasu15** [comment]
Can I work in it?

**Comment by apollonian** [comment]
@ShubhankarKG, I think it would be best to just remove these deprecated commands from the README. docz documentation is still in progress so it can be omitted for now.

**Comment by ShubhankarKG** [comment]
Yeah, figured that one out by spinning up the docz server. I'll fix up the readme then.

**Comment by apollonian** [comment]
Great, thanks.
