### ISSUE TITLE
onFocus and onBlur functionalities

### ISSUE THREAD

**Issue by KowsalyaPK** [devfolioco/react-otp-input#17]
- **Describe the Feature Request**
onFocus, onBlur, onInput are all default functionalities of any input, why not provide them here

**Comment by ajayns** [comment]
Multiple inputs are used for this particular component, so how exactly do you propose these event handlers work? We'll need to consider all cases from empty, to partially filled to fully filled inputs

**Comment by nestoralonso** [comment]
I may have a proposal for this on https://github.com/devfolioco/react-otp-input/pull/75

**Comment by Samibanley** [comment]
Can I give this one a try?

**Comment by codedoc7** [comment]
I would like to call a function that, when activated by a click, it will .concat the message string of the input box in focus, but I can't get the onFocus or onBlur to work.

**Comment by codedoc7** [comment]
> * **Describe the Feature Request**
>   onFocus, onBlur, onInput are all default functionalities of any input, why not provide them here

It is called because you run the function in the render method, you should pass function, not what they return.
Change -->
onFocus={this._onFocus()}
onBlur={this._onBlur()}
to this-->
onFocus={this._onFocus}
onBlur={this._onBlur}

**Comment by deepanshu2506** [comment]
working on it

**Comment by demarchenac** [comment]
Hi @prateek3255 ! I'll fix the suggestions for the closed PR
