### ISSUE TITLE
Nice to have UX if input is disabled

### ISSUE THREAD

**Issue by Sudarshan013** [devfolioco/react-otp-input#184]
- **Describe the Feature Request**
If the input is disabled, it would be better to show the not-allowed cursor pointer, instead of default on hover

-**Before Making the change**-

![ezgif-3-7c6510242800](https://user-images.githubusercontent.com/39631554/94957337-35c7d580-050b-11eb-9589-4750542331a0.gif)

- **After Making the change**

![after](https://user-images.githubusercontent.com/39631554/94957399-4bd59600-050b-11eb-92d6-051c26b3033d.gif)

**Comment by readmey** [comment]
Can I work on this issue?

**Comment by readmey** [comment]
What about using scss instead of css?

**Comment by apollonian** [comment]
Thanks for the suggestion! But, since we already have a `disabledStyle` prop that can facilitate such behaviour, I don't think it would be a good idea to add a cursor not-allowed style by default since the component is fairly un-opinionated when it comes to input styles.
