### ISSUE TITLE
BUG REPORT: isInputNum has no effect if non-numeric values are entered in the form input in demo

### ISSUE THREAD

**Issue by arc9693** [devfolioco/react-otp-input#187]
**Steps to reproduce the issue**: 
- Check the isInputNum box
- Enter alphabetic values in the "value" input in the sidebar

**Relevant error messages and/or screenshots**:
![ezgif com-gif-maker](https://user-images.githubusercontent.com/36061892/94972060-01adde00-0526-11eb-831a-d9dd502a4341.gif)

**Comment by arc9693** [comment]
@apollonian Could you please take a look? 
If approved, I would like to work on it.

**Comment by theWellHopeErr** [comment]
This bug also occurs when a text is pasted on the code box.

**Steps to reproduce the issue:**
1. Check the isInputNum box.


2. Paste an alphabetic text copied from the clipboard in the code boxes.

**Relevant error messages and/or screenshots:**
![ezgif com-gif-maker](https://user-images.githubusercontent.com/35459982/94984778-853eed80-056d-11eb-96e9-44cf106e565b.gif)

I would like to work on this issue if approved.

**Comment by prateek3255** [comment]
This has been fixed with v3
