### ISSUE TITLE
Separators should not be letters or numbers.It should be either hyphen,dot or whitespace.

### ISSUE THREAD

**Issue by Parshwa52** [devfolioco/react-otp-input#195]
Letters or Numbers doesn't look good as a separator so I would like to work on this issue. Could you assign me?
@apollonian 
- **Steps to reproduce the issue**:
Enter any letter or number in the separator field.
- **Relevant error messages and/or screenshots**:
[
![2020-10-03](https://user-images.githubusercontent.com/48866201/94987461-318bce80-0584-11eb-933d-c05fb2c4e9db.png)
](url)

**Comment by ShivamPrajapati-dev** [comment]
@apollonian I would lke to work on it.

**Comment by Parshwa52** [comment]
@apollonian 
I have worked perfectly on it in PR #199 
I also have added a demo video for it.
Can you please review it and get it merged?
