### ISSUE TITLE
Improve component props documentation

### ISSUE THREAD

**Issue by ShubhankarKG** [devfolioco/react-otp-input#198]
- **Describe the Feature Request**
The `docz` documentation can be improved by mentioning what each prop does, and maybe perhaps give an example of each.

- **Describe Preferred Solution**

Divide all props in

1. Required props
2. Optional props

For each optional prop, we can add a react example perhaps.

Followup to #197 
PS :- I would like to work on this, once finalized :)

**Comment by apollonian** [comment]
@ShubhankarKG sure, this would be great!

**Comment by ritikbanger** [comment]
The feature is available in: https://www.npmjs.com/package/react18-input-otp
