### ISSUE TITLE
Inserting the same number should trigger next input focus

### ISSUE THREAD

**Issue by demedos** [devfolioco/react-otp-input#20]
- **Steps to reproduce the issue**:
Write some number on the inputs
Click on an input an type the same value it has

- **Expected**:
The focus jumps to the next input

- **Actual behaviour**:
The focus remains on the same input

**Example**:
```
insert 3 - 4 - 5 - 6
click 3
type 3
```

**Comment by rimildeyjsr** [comment]
@ajayns @apollonian - Can I work on this?

**Comment by blenderskool** [comment]
@demedos Can I work on this? 🙂

**Comment by apollonian** [comment]
Please go ahead @blenderskool!

**Comment by binodgope30** [comment]
i am also facing same issue with the current version

**Comment by luccasmaso** [comment]
Waiting for this release also
