### ISSUE TITLE
Spam PR issue

### ISSUE THREAD

**Issue by ankiiitraj** [devfolioco/react-otp-input#200]
This is becoming a serious issue. 
People are spamming with PRs.

I propose to have a clear statement on Readme addressing the Spam issue and a warring!

**Comment by apollonian** [comment]
The spam has largely subsided as a result of the participation rule updates, so I do not believe a README advisory is needed at the moment. I am actively closing any invalid pull request on the repos, and we have reflected these updated rules in the Devfolio [blog post](https://devfolio.co/blog/devfolio-hacktoberfest-2020/) as well.
