### ISSUE TITLE
Add Error Message to display clarification on OTP failure

### ISSUE THREAD

**Issue by Kathuria** [devfolioco/react-otp-input#202]
- **Describe the Feature Request**
On submission of OTP inputs the result can be success or failure. On sucess, it's just next step what user wants but on failure component should display error message.

- **Describe Preferred Solution**
Error Message should be string value. It should be displayed when hasErrored: true (existing) is passed from props based on their conditions. Component will render errorMessage: 'Error Occurred, Please try again.' at bottom of inputs and above action buttons.

**Comment by Kathuria** [comment]
I can work on this issue if this can be a new feature for this component.

**Comment by A7abhilash** [comment]
I would like to solve this issue.

**Comment by apollonian** [comment]
Thanks for the suggestion! At the moment, it feels a little out of scope to me, but if we get more requests, I'd be happy to bump this up in the priority list.

**Comment by prateek3255** [comment]
Inputs can now be fully customized with v3
