### ISSUE TITLE
Automatically Prettify and Lint after every commit using Husky and Lint-Staged

### ISSUE THREAD

**Issue by nirmalhk7** [devfolioco/react-otp-input#203]
- **Describe the Feature Request**
Currently we're required to run `npm run format` to prettify the entire code and `npm run lint:fix` to fix the code. However, we can use Husky and lint-staged to automatically format those files which are staged into Git, making it more convenient.

- **Describe Preferred Solution**
We add Husky (which is a git hooks implementation for NodeJS projects) to execute our commands after pre-commit. We use lint-staged to filter out files which are in our staging area, and run our Prettify and ESLint commands there. This automation will massively increase code-maintenance in the future.

**Comment by nirmalhk7** [comment]
I'd love to implement this issue myself. @apollonian Please let me know. Thanks!

**Comment by apollonian** [comment]
Sure, this would certainly help a lot!
