### ISSUE TITLE
when input type is number maxLength=1 attribute is ignored

### ISSUE THREAD

**Issue by prashantbaid** [devfolioco/react-otp-input#21]
We can enter more than 1 number in an input field when input type is number. 

I think the issue is maxLength=1 does not work for `<inputType=number>`. 
Reference - https://stackoverflow.com/questions/18510845/maxlength-ignored-for-input-type-number-in-chrome

**Comment by ajayns** [comment]
Nice catch. I've added manual checking and so the issue should be resolved in the latest version. Please do check and let me know!

**Comment by apollonian** [comment]
Since we've added `min` and `max` attributes to the inputs (when isInputNum is set) with #23 I'm closing the issue. :)
