### ISSUE TITLE
Absence of proper documentation for the project

### ISSUE THREAD

**Issue by garimasingh128** [devfolioco/react-otp-input#217]
The project is not properly documented in terms of 
- PULL REQUEST TEMPLATE
- CONTRIBUTING GUIDELINES
- CODE OF CONDUCT
- ISSUE TEMPLATE

I would like to work on this issue and solve all the documentation issues!

**Comment by apollonian** [comment]
Closing this issue out now since the linked PR has been merged. Thanks!
