### ISSUE TITLE
Keypad opening closing issue

### ISSUE THREAD

**Issue by rb162215** [devfolioco/react-otp-input#22]
I am facing Keypad opening closing issue issue while typing the number in following browser with respective platform - 

Opera--> Iphone, Ipad

UC browser -> Iphone

When user type OTP in above browser then after enter first char of OTP keypaid down, to enter second char of OTP user need to click on input field.

Any solution of above problem.

**Comment by Ananya-96** [comment]
Hi, is there an update on this issue. Facing the same problem.

**Comment by apollonian** [comment]
@rb162215, @Ananya-96 Let me know if you are still facing issues with the keypad.

**Comment by apollonian** [comment]
v2 came with fixes for this issue. Feel free to reopen if the closing behaviour still persists!
