### ISSUE TITLE
Automate the build and deploy of demo

### ISSUE THREAD

**Issue by aromalanil** [devfolioco/react-otp-input#225]
# Description
This repo has an example site, which can be automatically built and deployed to GitHub pages using Github Action, just like in [devfolioco/react-copy-mailto](https://github.com/devfolioco/react-copy-mailto).

# Solution
Add a workflow file to do the same here.

**Comment by apollonian** [comment]
We now have automated deployment to GitHub Pages when pushed to master. 
Thank you for working on this @aromalanil! ✌️
