### ISSUE TITLE
Allow developer to specify from which input field should the separator be set 

### ISSUE THREAD

**Issue by brianpooe** [devfolioco/react-otp-input#24]
- **Describe the Feature Request**
I want to insert the separator only after the third input. example 123 - 456

**Comment by aesher9o1** [comment]
Is this thread active/ needed?

**Comment by Kuljeet-123** [comment]
@brianpooe can I work on this issue??

**Comment by brianpooe** [comment]
@Kuljeet-123 yes please.

**Comment by prateek3255** [comment]
This can now be done with v3 via the `renderSeparator` prop
