### ISSUE TITLE
Wrong way to handle digits OTP

### ISSUE THREAD

**Issue by blueberry6401** [devfolioco/react-otp-input#25]
When isInputNum = true, it should treat the input as string instead of number, because the OTP might start with '0'.

**Comment by ManojBahuguna** [comment]
https://github.com/devfolioco/react-otp-input/blob/9931449eb8c582a7d3a6530b4d12fff09a816cbc/src/lib/index.jsx#L142

don't think parsing to number is required here..

**Comment by IamDhana** [comment]
If otpType is number I am not able to type a number starting with 0. Ex 0123, 0345
