### ISSUE TITLE
Placeholder not updating after initial numInputs changes

### ISSUE THREAD

**Issue by Kathuria** [devfolioco/react-otp-input#255]
I noticed placeholder not working and getting console error - Length of the placeholder should be equal to the number of inputs.

Its working on initial load because default value i.e. numeric 4 is taken but after that changes to string from input fields.

On further analysis, found its broken only when numInputs changed from provided demo fields. The demo although marked to accept "number" but returns a string value.
HTML Input elements are documented to return string representing a number. See the documentation here

On other places like
isLastChild={i === numInputs - 1}
its working due to type conversion, 10 - '1', returns 9.

Note: Please check other places, according to me its not impacted

- **Steps to reproduce the issue**:
Update number in input field, after change input number count - Try adding placeholder.

- **Relevant error messages and/or screenshots**:
Length of the placeholder should be equal to the number of inputs.
![Placeholder not updating](https://user-images.githubusercontent.com/19428377/97777926-71e96700-1b99-11eb-8bd6-71a79538a919.PNG)

**Comment by ingOmarG** [comment]
is this already solved?

![image](https://user-images.githubusercontent.com/43019586/120036239-6e9a4a80-bfc5-11eb-82a3-f25d563722cf.png)

**Comment by ujjwal-shrivastava** [comment]
I think this issue is not resolved yet please author look into this.....

**Comment by ujjwal-shrivastava** [comment]
Try this:-

 <OtpInput
                        onChange={handleChange}
                        value={otp}
                        placeholder="----"
                        numInputs={4}
                        isInputNum={true}
                        inputStyle={{
                          color: "black",
                          width: "2.5rem",
                          height: "3rem",
                          margin: "0 1rem",
                          fontSize: "2rem",
                          borderRadius: 4,
                          border: "1px solid rgba(0,0,0,0.3)",
                        }}
                      />
