### ISSUE TITLE
Iphone Safari browser does not show typed numbers in OTP input fields.

### ISSUE THREAD

**Issue by ovbutt** [devfolioco/react-otp-input#265]
- **Steps to reproduce the issue**:
1) Open website in Iphones Safari browser 
2) Try entering numbers in input fields
3) The fields will take the input but will not show the value in fields.
- **Relevant error messages and/or screenshots**:
- 
![WhatsApp Image 2020-12-28 at 2 32 11 AM](https://user-images.githubusercontent.com/31251140/103180158-f6641780-48b4-11eb-9649-472395b913a1.jpeg)

**Comment by svota** [comment]
![image](https://user-images.githubusercontent.com/424767/103538811-50447e80-4e6d-11eb-9c68-4b740c8fe3bc.png)
I'm having this same problem. It is appearing for me on iphones 7, 8, and my ipad in Chrome and Safari.

**Comment by josephtesla** [comment]
I am also experiencing this issue. pls help

**Comment by ovbutt** [comment]
@josephtesla @svota
One workaround can be you can decrease the font size in case of safari mobile web. This is what I did and it worked for me

**Comment by manjariParthiban** [comment]
@josephtesla setting 'padding:0' in inputStyle prop works

**Comment by ritikbanger** [comment]
The feature is available in: https://www.npmjs.com/package/react18-input-otp

**Comment by praty22** [comment]
Setting padding:0 works,
But then how to apply padding styles on input?

**Comment by praty22** [comment]
> Setting padding:0 works, But then how to apply padding styles on input?

width: 49px !important;
height: 46px;
padding: 0

Found a workaround!
This will help to provide the custom design to inputs without giving padding,
Padding needs to be kept at 0 otherwise the number does not appear. This is a bug I guess.

**Comment by prateek3255** [comment]
You can now fully customize the input elements with v3

**Comment by Madanraj1** [comment]
> padding: 0

yeah this worked
