### ISSUE TITLE
onKeyPress or onKeyDown feature is not available . 

### ISSUE THREAD

**Issue by Geetendra1** [devfolioco/react-otp-input#266]
- **Describe the Feature Request**
I did not see any doc related to onKeyPress  or what so ever . please mention it here if available or add it if possible . 
- **Describe Preferred Solution**

**Comment by rajeshindium** [comment]
when can I accept this feature

**Comment by shahid7292** [comment]
Anything on this feature

**Comment by patilniranjan7** [comment]
I need same for capture On Press Enter

**Comment by ritikbanger** [comment]
The feature is available in: https://www.npmjs.com/package/react18-input-otp

**Comment by prateek3255** [comment]
Duplicate of #352
