### ISSUE TITLE
Disable autoComplete

### ISSUE THREAD

**Issue by nsisodiya** [devfolioco/react-otp-input#268]
![image](https://user-images.githubusercontent.com/333455/106474800-45602680-64cb-11eb-9c56-1f22835d580b.png)

since OTP component is created using input element, the browser is by-mistake treating as a field for email automatically try to add email. Since OTP component takes only one char, only first char is shown above.
Since, I don't have control over input element, I cannot add `autocomplete='off'` to this component.
So, kindly add a provision to disable auto-complete. 
Best, one should be able to add any attribute  like this

```
<OtpInput
        value={this.state.otp}
        htmlAttrs={{
              autocomplete: 'off',
              name: 'number'
        }}
        onChange={this.handleChange}
        numInputs={6}
        separator={<span>-</span>}
      />
```
`htmlAttrs` will got to input elements.

**Comment by prateek3255** [comment]
You can now fully customize the input element with v3
