### ISSUE TITLE
Not Working On Enter Key

### ISSUE THREAD

**Issue by Usama-Ahmad** [devfolioco/react-otp-input#270]
- As event is not given, onChange method only returns OTP code what should I do if I want to submit it on pressing enter.

**Comment by littlefinger42** [comment]
Wrap your OtpInput in a `<form>` element with onSubmit, then use `<Button type="submit"/>`

https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/submit_event

**Comment by Usama-Ahmad** [comment]
Totally cool done it already. anyway thanks for helping

**Comment by apollonian** [comment]
Happy to help with other questions you may have!

**Comment by denishrana09** [comment]
> Wrap your OtpInput in a `<form>` element with onSubmit, then use `<Button type="submit"/>`
> 
> https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/submit_event

For those, who don't want to show the button, simply add css, `display: none` to the button
