### ISSUE TITLE
expose input properties, like onFocus

### ISSUE THREAD

**Issue by gperdomor** [devfolioco/react-otp-input#274]
- **Describe the Feature Request**
Please add a way to pass some properties to all input fields, this is useful to detect if the input is touched, to trigger validation errors, also should be useful to integrate with formik

**Comment by vitorbertolucci** [comment]
This would also be useful to pass a `name` prop to allow extensions like 1Password autofill the input when it appears.

**Comment by prateek3255** [comment]
You can now fully customize the input element with v3
