### ISSUE TITLE
When providing number type value getting error

### ISSUE THREAD

**Issue by RishabhReactJS** [devfolioco/react-otp-input#277]
I'm using .TSX file, in that when I'm passing value as number type it's giving error during build time,
 Type 'number' is not assignable to type 'string'.
But in documentation it's mentioned value can be string/number.

- **Steps to reproduce the issue**:

- **Relevant error messages and/or screenshots**:

**Comment by ritikbanger** [comment]
The feature is available in: https://www.npmjs.com/package/react18-input-otp

**Comment by prateek3255** [comment]
v3 is fully type safe now
