### ISSUE TITLE
isInputNum

### ISSUE THREAD

**Issue by Dharmadurai95** [devfolioco/react-otp-input#279]
- ** I have create a opt field i added isInputNum= true event someone copy paste the text it's accept can you please consider this problem **

- ** <input  onDrop="return false" onPaste="return false" autocomplete=off />
 **

**Comment by ritikbanger** [comment]
The feature is available in: https://www.npmjs.com/package/react18-input-otp

**Comment by prateek3255** [comment]
This has been fixed with v3
