### ISSUE TITLE
Input Box Style

### ISSUE THREAD

**Issue by Deexit1** [devfolioco/react-otp-input#282]
- Input boxes should have styling choice:- box/underline

- style choice also have to be an props choice. Developer can make this by adding props to the main component and add the style by choosing the props.

**Comment by ritikbanger** [comment]
The feature is available in: https://www.npmjs.com/package/react18-input-otp

**Comment by Kritika0035** [comment]
I want to do this. May I?

**Comment by prateek3255** [comment]
You can now fully customize the input component with v3
