### ISSUE TITLE
is this already solved?

### ISSUE THREAD

**Issue by ingOmarG** [devfolioco/react-otp-input#288]
- **Describe the Feature Request**
-is this already solved?
![image](https://user-images.githubusercontent.com/43019586/120036137-47dc1400-bfc5-11eb-937f-a9e885dbe9b7.png)

- **Describe Preferred Solution**

**Comment by apollonian** [comment]
Hey @ingOmarG! This error is shown when the placeholder and input length do not match. For eg, if your input is of the length four, you must have a placeholder string of the same length ("1234", "XBRM", etc).

**Comment by ritikbanger** [comment]
The feature is available in: https://www.npmjs.com/package/react18-input-otp
