### ISSUE TITLE
Auto filling otp input in safari.

### ISSUE THREAD

**Issue by sugamantra** [devfolioco/react-otp-input#290]
- **Describe the Feature Request**
When OTP sent on a mobile on which otp screen is opened, to fill the otp we need to pass autocomplete property to input html tag as "one-time-code".
- **Describe Preferred Solution**
Provide a prop to be passed to set autocomplete property of input tag.
Refer [link](https://web.dev/sms-otp-form/#:~:text=With%20autocomplete%3D%22one%2Dtime,for%20the%20user%20to%20enter) for more details of this implementation.

**Comment by rake7h** [comment]
Facing the same. @sugamantra did you find any workaround?

**Comment by carryall** [comment]
Does a workaround with a hidden input with `autoComplete="one-time-code"` and an onChange function to sync the value from the hidden input to the OTP input works? 💭

**Comment by NareshItla** [comment]
@ajayns , @apollonian  Can u check this once need help on this feature. @carryall , @sugamantra  did u guys get any solution for this issue. I am also facing same.

**Comment by ritikbanger** [comment]
The feature is available in: https://www.npmjs.com/package/react18-input-otp

**Comment by prateek3255** [comment]
You can now fully customize the inputs with v3
