### ISSUE TITLE
BUG REPORT: When isInputSecure check is opened(true) with combination of isInputSecure keyboard changes from numeric to text-input

### ISSUE THREAD

**Issue by Mohammad-Bilal-Bhatti** [devfolioco/react-otp-input#292]
- **Describe the Feature Request**

Feature request for correct keyboard appearance

- **Describe Preferred Solution**

Should open numeric keyboard when isInputSecure & isInputNum both checks are open(true)

**Comment by Sai-Rama-Krishna** [comment]
Should open numeric keyboard when isInputSecure & isInputNum both checks are open(true)
