### ISSUE TITLE
dependency error: Not working with react 17

### ISSUE THREAD

**Issue by alireza-sharifpour** [devfolioco/react-otp-input#295]
I just want to install this package and i got dependency error:

`npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: x@0.1.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"17.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.2.0" from react-otp-input@2.3.1`

i used --legacy-peer-deps but i just wanted to inform you.

**Comment by darkmatter18** [comment]
Same here

**Comment by EdwardMovsesyan91** [comment]
Same here

**Comment by daryl-07** [comment]
Same here (2)

**Comment by pragati9** [comment]
same issue

**Comment by avinash-wissen** [comment]
same issue

**Comment by EmmanuelAmodu** [comment]
Temporary fix https://www.npmjs.com/package/react-otp-input-rc-17
`npm i react-otp-input-rc-17`

**Comment by JPStrydom** [comment]
Could we not simply bump the peer dependencies to:
```
 "peerDependencies": {
    "react": "^17.0.0",
    "react-dom": "^17.0.0"
  },
```
?

**Comment by ritikbanger** [comment]
The feature is available in: https://www.npmjs.com/package/react18-input-otp

**Comment by shtbik** [comment]
You can resolve it manually in the `package.json` with the [overrides](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides) rule for `npm` (^8) or with `resolutions` for `yarn`:

**NPM example:**
```json
"overrides": {
    "react-otp-input": {
      "react": "$react",
      "react-dom": "$react-dom"
    }
 }
```

**Comment by ritikbanger** [comment]
Hello @shtbik Please go with this new package: https://www.npmjs.com/package/react18-input-otp

**Comment by prateek3255** [comment]
v3 now works with React 17 and 18
