### ISSUE TITLE
Need option to change the border color of focus

### ISSUE THREAD

**Issue by vidhyeshpatil** [devfolioco/react-otp-input#297]
- **Describe the Feature Request**

Currently not able to change / override the border color on focus i.e. "focusStyle" - Default it's blue color.

- **Describe Preferred Solution**

focusStyle - give the option to override the same

**Comment by TheAhmadSami** [comment]
Just change the outline not the border

**Comment by RajuSuranagi** [comment]
Setting `focusStyle={{ outline: 'none', border: '2px solid #05DEBA', borderRadius: '8px' }}` works. But why do I need to mess with the outline if all I want is border?

**Comment by TheAhmadSami** [comment]
Because outline is a default css property for inputs, checkboxes, buttons and other html tags. So you **must** overwrite it's value even when you just work with borders.

**Comment by ritikbanger** [comment]
The feature is available in: https://www.npmjs.com/package/react18-input-otp

**Comment by prateek3255** [comment]
You can now fully customize the input element with v3.
