### ISSUE TITLE
Page automatically scrolls because of focus to the next element

### ISSUE THREAD

**Issue by debjits1** [devfolioco/react-otp-input#300]
In iOS devices, I am facing this issue. I am using react-otp-input inside a material-ui dialog. Whenever I add a new number in the input, it focuses on the next input, and the page in the background auto scrolls. Also, the dialog flickers a lot on the same event.
This happens becuase the focus method automatically try to scroll to element. Is there a way we can stop the autoscroll on focus?

- **Steps to reproduce the issue**:
- Use react-otp-input inside a material ui Dialog component
- Fix the Dialog element at bottom of the screen with css properties
- Try to input number in otp input component

**Comment by roshan-p** [comment]
@debjits1 Have you fixed it ?

**Comment by LanhNguyen97** [comment]
@debjits1 Have you fixed it?

**Comment by debjits1** [comment]
No, still did not find any solution

**Comment by ritikbanger** [comment]
The feature is available in: https://www.npmjs.com/package/react18-input-otp

**Comment by prateek3255** [comment]
Can you add a reproducible sandbox/demo video here, and reopen the issue again once fixed?
