### ISSUE TITLE
How to Style the Input Container

### ISSUE THREAD

**Issue by pradeea** [devfolioco/react-otp-input#304]
- **Describe the Feature Request**
How to style the Input Container i couldn't see how to style this i have checked docs but im disappointed that i couldn't find how to style the input container
- **Describe Preferred Solution**

**Comment by Mominadar** [comment]
Hi, you can use the `containerStyle` prop to style the whole container. For styling individual inputs, use `inputStyle` prop.

**Comment by ritikbanger** [comment]
The feature is available in: https://www.npmjs.com/package/react18-input-otp
