### ISSUE TITLE
Backspace delete specific input field and stay on it

### ISSUE THREAD

**Issue by emran-jatri** [devfolioco/react-otp-input#306]
Backspace delete specific input field and stay on it. I see many issues and pull requests in this git, but after solving this issue git and npm are not updated? I need solved things right now, can someone please help me with how to do that? when I click on backspace it should work like the delete button on the keyboard. thanks you

**Comment by Joojo7** [comment]
@emran-jatri Did you find a solution to this?

**Comment by ritikbanger** [comment]
The feature is available in: https://www.npmjs.com/package/react18-input-otp
