### ISSUE TITLE
Make aria label dynamic

### ISSUE THREAD

**Issue by kchakraborty-94** [devfolioco/react-otp-input#307]
- **Describe the Feature Request**
- The aria label for the input is hardcoded as **Please enter verification code.** . This should be a dynamic value.

- **Describe Preferred Solution**
- The aria label should be passed as a prop. The prop should be optional. If passed, should be used, otherwise should fall back to the current one

**Comment by ritikbanger** [comment]
The feature is available in: https://www.npmjs.com/package/react18-input-otp

**Comment by prateek3255** [comment]
You can now customize the input with v3, so you can override the aria-label prop according to your needs
