### ISSUE TITLE
isInputNumber - blank value when setting zero as inputs initial value

### ISSUE THREAD

**Issue by joao-arvins** [devfolioco/react-otp-input#31]
**Steps to reproduce the issue**:
- input 0 in the first input - input will become empty instead if having the value '0'
- this will happen for all inputs being set after one of the input values gets updated to something other than zero
- if you try to update one value from 1-9 to 0 then some strange behaviour will hapen (one of the inputs will get blank, not necessarily the one being updated)

![image](https://user-images.githubusercontent.com/5934156/64249188-07905480-cf0b-11e9-80fe-1001b013df27.png)

**Comment by joao-arvins** [comment]
This PR should fix the issue: #30

**Comment by Praneeth543** [comment]
is this merged in the latest version  ?

**Comment by apollonian** [comment]
@joao-arvins, @Praneeth543 this is now fixed with [2.0.0](https://github.com/devfolioco/react-otp-input/releases/tag/v2.0.0)
Please upgrade/retest and let me know if you still notice it.
