### ISSUE TITLE
Make test id dynamic

### ISSUE THREAD

**Issue by carryall** [devfolioco/react-otp-input#315]
- **Describe the Feature Request**
  - To support [overridden test id attribute](https://testing-library.com/docs/queries/bytestid/#overriding-data-testid) name

- **Describe Preferred Solution**
  provide another attribute for custom test attributes
  ```js
  <OtpInput value={otp} onChange={onOTPChange} numInputs={4} testIds={ { data-test: 'input-otp' } } />
  ```
  then the test attribute added to the input like `data-test='input-otp-0'`, `data-test='input-otp-1'`, `data-test='input-otp-2'`, `data-test='input-otp-3'`

**Comment by ritikbanger** [comment]
The feature is available in: https://www.npmjs.com/package/react18-input-otp

**Comment by prateek3255** [comment]
You can now customize the input with v3
