### ISSUE TITLE
How to add additional attributes to input field.

### ISSUE THREAD

**Issue by v4irajvimu** [devfolioco/react-otp-input#318]
- **Describe the Feature Request**
- How can i add additional attributes to input elements like **inputmode="numeric"**

- **Describe Preferred Solution**

**Comment by ritikbanger** [comment]
The feature is available in: https://www.npmjs.com/package/react18-input-otp

**Comment by prateek3255** [comment]
The input field is not fully customizable in v3 and you cna pass any inputProps you want directly to the input field itslef
