### ISSUE TITLE
Gboard’s clipboard suggestions feature not working properly with React Otp Input

### ISSUE THREAD

**Issue by prograk** [devfolioco/react-otp-input#323]
- **Describe the Feature Request**

When you copy OTP from sms and it shows in Gboard top as suggestion and when you click on it, doesn't get pasted in React Otp Input boxes.

- **Describe Preferred Solution**

When clicked on suggestion it should fill all boxes like how it happens in normal copy paste.

![photo_2021-12-13 12 09 52](https://user-images.githubusercontent.com/20883002/145764344-f7cfcc91-814f-4f45-96fa-35c71028fedc.jpeg)

**Comment by KranthiJulakantiNiro** [comment]
Facing same issue

**Comment by sgarchavada** [comment]
Any update on this one

**Comment by KranthiJulakantiNiro** [comment]
Check this out
https://github.com/devfolioco/react-otp-input/issues/113#issuecomment-998148875
@sgarchavada

**Comment by shubham-saxena-pdgt** [comment]
https://www.npmjs.com/package/react-otp-input-2

**Comment by ritikbanger** [comment]
The feature is available in: https://www.npmjs.com/package/react18-input-otp

**Comment by prateek3255** [comment]
Can you confirm if this issue still exists with v3 and reopen the issue if it does?
