### ISSUE TITLE
Keyboard layout auto switches from numbers to characters in mobiles.

### ISSUE THREAD

**Issue by aKshayKadam03** [devfolioco/react-otp-input#327]
When we try to enter the OTP in mobiles. The keyboard layout auto switches from Number to Characters/Alphabets layout because the OTP component re-renders on every input.
 
The above issue can be reproduced on the official demo link. 
i.e https://devfolioco.github.io/react-otp-input/

#### Steps to reproduce:
* Open the link in mobile phone.
* Switch to number keyboard.
* Add a number
* The keyboard will switch back to characters/alphabets keyboard layout

#### Preferred Solution 
* The keyboard layout state should persist.

**Comment by therealdrtroll** [comment]
Please check the following clip:
https://www.loom.com/share/eadc9d07d36a4211b758464a356bc6ba

* Reproduced on:
   * Phone: Nokia 6.1 plus 
   * OS: Android 10

* Also reproducible on iOS 15.2

**Comment by Kiran636** [comment]
use attribute
 isInputNum={true}

**Comment by aKshayKadam03** [comment]
> https://devfolioco.github.io/react-otp-input/

The OTP has both alphabets and numbers. So can't fix it to just numbers.

**Comment by prateek3255** [comment]
You can now customize the type with the `inputType` prop in v3.

**Comment by dhanushpani** [comment]
does anyone resolved this?
