### ISSUE TITLE
Update of the peer dependency package from v16 to v17

### ISSUE THREAD

**Issue by Tushar-Maity** [devfolioco/react-otp-input#328]
The React version should be updated from v16 to v17.

**Comment by SandeshKandukuri** [comment]
> The React version should be updated from v16 to v17.

For me, its showing error that react version of react-otp-input is v16, and my project is of v17, is there any solution to this?

**Comment by Mehran91z** [comment]
+1 for update your React dependency version to 17.
Thanks.

**Comment by askariacc** [comment]
Is there any update on it?

**Comment by kandukuriSandesh** [comment]
"react-otp-input-rc-17": "^2.4.1-minor", install this dependency , this is for v17

**Comment by askariacc** [comment]
> 
Why is this package linked to the actual repo?
Where is the appropriate source code?

**Comment by Sean-Y-X** [comment]
React18 now. Pls.

**Comment by ritikbanger** [comment]
The feature is available in: https://www.npmjs.com/package/react18-input-otp

**Comment by prateek3255** [comment]
v3 now supports both React 17 and 18
