### ISSUE TITLE
shouldAutoFocus does not work on "ubuntu Mozila Firefox"

### ISSUE THREAD

**Issue by keshikashviligio** [devfolioco/react-otp-input#334]
Firefox: 
![image](https://user-images.githubusercontent.com/6962834/153828823-bb1ef7f2-281e-4a08-a61c-592f4b4ddb81.png)
Chrome:
![image](https://user-images.githubusercontent.com/6962834/153829074-2bbe2e1a-a114-4703-b1f7-4b2b1e727d08.png)

**Comment by prateek3255** [comment]
Can you check if this problem still exists with v3, and reopen the issue if it does?
