### ISSUE TITLE
Backspace button doesn't work properly

### ISSUE THREAD

**Issue by Joojo7** [devfolioco/react-otp-input#346]
The backspace button doesn't remove the previous number on the first press, it only selects the previous number. Is there a fix for this or can this be fixed? 
![Screenshot 2022-05-20 at 1 25 17 PM](https://user-images.githubusercontent.com/30333594/169457003-70e2fe87-af51-4712-86ac-0c633fb577a8.png)

**Comment by ritikbanger** [comment]
The feature is vailable in: https://www.npmjs.com/package/react18-input-otp

**Comment by prateek3255** [comment]
Can you see if its still a problem with v3, and reopen the issue if it still exists?

**Comment by vpzomtrrfrt** [comment]
This is still a problem with v3.
