### ISSUE TITLE
Migrate to Hooks

### ISSUE THREAD

**Issue by ojaswa1942** [devfolioco/react-otp-input#35]
The code presently uses class components & lifecycle methods.
However, React 16.8.0 release introduces a more intuitive & functional approach towards development which is more likely to be used in the future.

**Steps to resolve the issue**:
  Replace Class and Class-based methods (state, lifecycle, PureComponent etc.) to functional approach (useState, useEffect, memo, etc.)

**Comment by V1shvesh** [comment]
May I pick this issue up?

**Comment by apollonian** [comment]
This sounds amazing. ✨ 
Please go ahead @V1shvesh!

**Comment by V1shvesh** [comment]
Hey @apollonian! It seems to me that the file `src/lib/index.jsx` uses TSX, but the file extension doesn't reflect that fact. Is there any reason behind this?

**Comment by apollonian** [comment]
We don't use TypeScript although we've added annotations for Flow.

https://github.com/devfolioco/react-otp-input/blob/master/src/lib/index.jsx#L1

**Comment by V1shvesh** [comment]
Got it! I tried configuring Flow for VS Code, but I am getting this error:
```
[react-otp-input/.flowconfig] Failed to start flow Error: 
Flow version 0.73.0 doesn't support 'flow lsp'.
Please upgrade flow to version >=0.75.
```

The latest version of Flow: 0.109.0, no idea about the backward-compatibility.

**Comment by apollonian** [comment]
Hmm, looks like we'll have to upgrade it.

**Comment by V1shvesh** [comment]
Alright then, I'll do that as well :+1:

**Comment by V1shvesh** [comment]
Hey @apollonian!

So I kinda did a complete re-haul of the whole file, and I had to install `@types/react` for React type definitions. I am almost done with the refactor and will post a PR soon!

**Comment by V1shvesh** [comment]
https://github.com/devfolioco/react-otp-input/blob/bb387f608499a84676632690a8d8dc1c51d13a5a/src/lib/index.jsx#L105

Was 'tel' supposed to be 'text'?

**Comment by apollonian** [comment]
Awesome, looking forward to it. This reminds that we should also update the prop table in the README.

**Comment by V1shvesh** [comment]
Wow, I completely missed that table! You're right, that should reflect the finalized default props.

**Comment by darkmatter18** [comment]
@apollonian Seems like the issue still exists. So, Can I work on it?

**Comment by apollonian** [comment]
Sure, @darkmatter18. Some work has been done in this direction already. Checkout the https://github.com/devfolioco/react-otp-input/tree/v2 branch (it is out of sync with master — does not contain the latest changes).

**Comment by darkmatter18** [comment]
@apollonian Thanks. I have one more query. Why using flow. We can use TypeScript for better type support

**Comment by nanipunepalle** [comment]
@apollonian I have migrated all the components following @darkmatter18 pull request including demo app components into functional react-hooks

**Comment by prateek3255** [comment]
This has been fixed with v3
