### ISSUE TITLE
Please make the package work for v18.

### ISSUE THREAD

**Issue by mukhammadalime** [devfolioco/react-otp-input#350]
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: react-otp-input@2.4.0
npm ERR! Found: react@18.1.0
npm ERR! node_modules/react
npm ERR!   react@"^18.1.0" from the root project
npm ERR!   peer react@"^18.0.0" from @testing-library/react@13.3.0
npm ERR!   node_modules/@testing-library/react
npm ERR!     @testing-library/react@"^13.3.0" from the root project
npm ERR!   5 more (react-dom, react-paginate, react-router, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.2.0" from react-otp-input@2.4.0
npm ERR! node_modules/react-otp-input
npm ERR!   react-otp-input@"^2.4.0" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: react@16.14.0
npm ERR! node_modules/react
npm ERR!   peer react@"^16.2.0" from react-otp-input@2.4.0
npm ERR!   node_modules/react-otp-input
npm ERR!     react-otp-input@"^2.4.0" from the root project

**Comment by MahdiMhqq** [comment]
see https://github.com/MahdiMhqq/react18-otp-input

**Comment by ritikbanger** [comment]
The feature is vailable in: https://www.npmjs.com/package/react18-input-otp

**Comment by prateek3255** [comment]
v3 supports react-18 now
