### ISSUE TITLE
The component is not mobile-friendly

### ISSUE THREAD

**Issue by YunusEmreAlps** [devfolioco/react-otp-input#351]
- **Describe the Feature Request**
- I used this component in my project but it is not mobile-friendly.
![Screenshot (455)](https://user-images.githubusercontent.com/44679555/177551320-3ec2fc0d-5bf3-4aa6-bbd6-b6409ce1d3f9.png)
![Screenshot (457)](https://user-images.githubusercontent.com/44679555/177551329-f9a165f8-4ffd-4fd6-9340-44eb50fc4eb8.png)

- **Describe Preferred Solution**
I think this problem can be solved with a loop instead of using the div component.

**Comment by ritikbanger** [comment]
The feature is vailable in: https://www.npmjs.com/package/react18-input-otp

**Comment by prateek3255** [comment]
You can now customize the input component with v3
