### ISSUE TITLE
Auto upgrade to be compatible with  latest react versions 

### ISSUE THREAD

**Issue by CodeNinja96x** [devfolioco/react-otp-input#359]
- **Describe the Feature Request**
    please make the package compatible to latest React version, please find below the error encountered, while trying to install the 
 package for react 17.0.2
![image](https://user-images.githubusercontent.com/17404158/184977983-5d9b4d17-e2b1-4160-b1b3-0269e92fad0e.png)

- **Describe Preferred Solution**
- can have a auto-upgrading script that updates the package with the latest react version or script to adjust the package with the users react version.

**Comment by nmaddp1995** [comment]
I face the same issue @@.
--force seem not a good work around for it

**Comment by prateek3255** [comment]
v3 now supports both React 17 and 18.
