### ISSUE TITLE
Improvements to the demo/documentation site (Move to Storybook or docz)

### ISSUE THREAD

**Issue by apollonian** [devfolioco/react-otp-input#36]
Right now we use a custom built site (https://devfolioco.github.io/react-otp-input/) for demo-ing the component. Although, it is fairly primitive and lacks features such as a prop table, etc.

We could use docz (https://www.docz.site/) or Storybook (https://storybook.js.org) for the same. While I really like the fact that docz is minimal (and supports TypeScript out of the box), Storybook has a large & useful plugin/addon ecosystem.

Would love to hear thoughts on this! ✨

**Comment by anikethsaha** [comment]
I would like to work on this 👍

**Comment by apollonian** [comment]
Sure, please go ahead @anikethsaha!

**Comment by shivamkainth** [comment]
@apollonian Can I work on this as well ?

**Comment by anikethsaha** [comment]
@shivamkainth ,I am currently adding `docz` in this, so I guess we can work on the components docs then . 
what do you think !?

**Comment by apollonian** [comment]
Hey @shivamkainth! Like @anikethsaha mentioned in the previous comment, once docz is all set-up we could work on adding the component playground and other info.

**Comment by ankiiitraj** [comment]
Can be closed?
