### ISSUE TITLE
How to style filed input style

### ISSUE THREAD

**Issue by bhautikagile** [devfolioco/react-otp-input#361]
when I'm trying to add style in filed input's parent div, can't put style style on filed input or parent div. Show how to add style on filed input

**Comment by Kritika0035** [comment]
May I do this?

**Comment by Ripudaman4742** [comment]
There is prop called inputStyle, you can pass your values over there

**Comment by prateek3255** [comment]
Apart from `inputStyle` you can pass your own `input` component with v3 now.
