### ISSUE TITLE
Add dynamic value for aria-lable <OTPinput>

### ISSUE THREAD

**Issue by sagarsinha-code** [devfolioco/react-otp-input#366]
I want to change the value of aria-lable for input tag. Unfortunately not able to do so because its not getting passed as a props and its value is hardcoded.

Any solution for this will be helpful.
Thanks

**Comment by Rajesh-M2P** [comment]
test

**Comment by Rajesh-M2P** [comment]
wcwc

**Comment by prateek3255** [comment]
This can now be done with v3, as you can pass your own input component. So you can override the currently passed `aria-label` to the component
