### ISSUE TITLE
npm i react-otp-input

### ISSUE THREAD

**Issue by hung2003attack** [devfolioco/react-otp-input#369]
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: client@0.1.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"^18.2.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.2.0" from react-otp-input@2.4.0
npm ERR! node_modules/react-otp-input
npm ERR!   react-otp-input@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /home/hung/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hung/.npm/_logs/2022-11-09T08_53_28_967Z-debug-0.log

**Comment by hung2003attack** [comment]
I can't install

**Comment by jashenco** [comment]
Use yarn add react-otp-input

**Comment by kvraamkey** [comment]
@hung2003attack if you're in NPM try as below

`rpm i react-otp-input --legacy-peer-deps`

**Comment by pacarvalho** [comment]
Is this library still accepting pull requests and updating the NPM registry? It would be great to update the peer dependencies...

**Comment by Rajesh-M2P** [comment]
`jhgfdfghjklwqd`

**Comment by Rajesh-M2P** [comment]
`sqsdfghjdkjdd
dcdcdc
cdcdc
cwcwcwc`

**Comment by Rajesh-M2P** [comment]
@kvraamkey - test

**Comment by Rajesh-M2P** [comment]
sdfsad
as
ada
dsa






sdasd

**Comment by Rajesh-M2P** [comment]
`dkjbgkjdbfgdssdfg dsfg dsfg ds gdsfg





sdgsdfdsfgs
`
