### ISSUE TITLE
OTP input taking spacebar(' ') as input

### ISSUE THREAD

**Issue by utkarsh22garg** [devfolioco/react-otp-input#38]
- OTP is taking spacebar as input
 
 OTP is a number. So it can't have inputs like spacebars. So the input **spacebar** should be ignored for this.

![issue-open-source](https://user-images.githubusercontent.com/31355903/66114733-1b53d700-e5ed-11e9-8d75-17072acd310c.PNG)

**Comment by blenderskool** [comment]
@apollonian I can work on this bug

**Comment by apollonian** [comment]
Fixed with #42!
We'll push a fix for this in the upcoming release.
Thanks.

**Comment by utkarsh22garg** [comment]
@apollonian Happy to hear that 😊
