### ISSUE TITLE
How to set mobile keyboard to use only numpad? 

### ISSUE THREAD

**Issue by rijans** [devfolioco/react-otp-input#384]
- **Steps to reproduce the issue**:

- **Relevant error messages and/or screenshots**:

How to set mobile keyboard to use only numpad?

**Comment by Rajesh-M2P** [comment]
qwdqwd
qwdqw







qwqwdqw


qwdqwd




qwd
qwd


qw
qwd
qw
dqwdqwwd

**Comment by prateek3255** [comment]
You can now customize the type of the input being rendered with the new `inputType` prop in v3.
