### ISSUE TITLE
Paste from clipboard does not work if inputType number

### ISSUE THREAD

**Issue by mutedSpectre** [devfolioco/react-otp-input#399]
Hello.
Using the latest version (v3), it was found that pasting from the clipboard does not work if `inputType` is set to 'number'.
- **Steps to reproduce the issue**:
1. Go to [live demo](https://devfolioco.github.io/react-otp-input/)
2. Set inputType - number
3. Copy the string of numbers to the clipboard (e.g. 1234)
4. Try to paste from clipboard

**Comment by prateek3255** [comment]
Okay looks like we'll need to update the [handlePaste method](https://github.com/devfolioco/react-otp-input/blob/main/src/index.tsx#L180) to make it work for number inputs. Would you like to work on this @mutedSpectre?

**Comment by mutedSpectre** [comment]
@prateek3255 check my PR please.

**Comment by AlvianOng** [comment]
is there any progress on this bug? I just experienced the same issue when migrate to v3

**Comment by riteshsainju** [comment]
Any updates on this issue?

**Comment by prateek3255** [comment]
Sorry for the delay here this issue was fixed with v3.0.3
