### ISSUE TITLE
Border color change on click

### ISSUE THREAD

**Issue by AnushkaTyagi26** [devfolioco/react-otp-input#410]
As I have raised an issue yesterday regarding Border color change when we click on an input value, but I am not able to change color.
And yes, I am using the V3 of this library and styling doesn't change even on using onfocus.

Can you tell me how you will change it...?

**Comment by prateek3255** [comment]
@AnushkaTyagi26 As mnetioned previously the input is fully customizable, so you can add a class to the input with the [focus selector](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus), to change the border color
