### ISSUE TITLE
Keyboard paste (Ctrl+V) does not work on Chrome

### ISSUE THREAD

**Issue by amhrn** [devfolioco/react-otp-input#411]
- **Steps to reproduce the issue**:

1. Use Google Chrome (this works on Firefox)
2. Copy the OTP
3. Try pasting with the keyboard (Ctrl+V)

- But when use the context menu to paste it works.

**Comment by prateek3255** [comment]
@amhrn Can you add a video or screenshot or something reproducing it? Because it seems to be working fine for me on https://devfolioco.github.io/react-otp-input/

Also can you confirm that you are on the latest version of the library (v3.0.4) which contains fixes for copy/paste issues?

**Comment by amhrn** [comment]
Thanks, updating worked!
