### ISSUE TITLE
OTP inputs keeps going out of view whenever i add a padding 

### ISSUE THREAD

**Issue by sylvahh** [devfolioco/react-otp-input#412]
- **Steps to reproduce the issue**:
- When I set the Otp component and try to add padding to increase the size of the input box  the text goes out of view

- **Relevant error messages and/or screenshots**:

**at default**
![defualt ](https://github.com/devfolioco/react-otp-input/assets/80820453/e3203d86-96b9-4423-8365-71c06e3939e9)

** at padding 1px**
![input@p-1](https://github.com/devfolioco/react-otp-input/assets/80820453/d3bfb5f5-3c24-4ec0-8b68-119c422502b6)

**at desired size**
![input@desieredsize](https://github.com/devfolioco/react-otp-input/assets/80820453/efcd168b-84ec-4602-ae76-eeaf1198c55e)

**code snippet**
![code snippet ](https://github.com/devfolioco/react-otp-input/assets/80820453/04d04c3b-bc22-4e15-974d-f44c6c6ba0fa)

**Comment by prateek3255** [comment]
Can you update to the latest version and use `skipDefaultStyles` prop? That would remove the default styles that are applied to the input
