### ISSUE TITLE
Request For A New Function

### ISSUE THREAD

**Issue by prasenjitDigitalFriend** [devfolioco/react-otp-input#413]
- **Describe the Feature Request**
- Please add a function that will trigger immediately after completing the input

- **Describe Preferred Solution**
- Check the input length; if the length is equal to the value length, then the function will automatically be called.

**Comment by prateek3255** [comment]
Since the onChange event handler is under your control, its better that you trigger whatever update that is needed from your application itself when the OTPInput is filled
