### ISSUE TITLE
Auto fill Not working on Android and IOS

### ISSUE THREAD

**Issue by Datta-Telukunta** [devfolioco/react-otp-input#417]
Can we have the fix similar to below on V3?
[Commit Link](https://github.com/hunghg255/reactjs-otp-input/commit/e4262e5aa68abda9f2cdcf2faaccd1a83d10d58f)

_Originally posted by @Datta-Telukunta in https://github.com/devfolioco/react-otp-input/issues/322#issuecomment-1735823169_

**Comment by prateek3255** [comment]
Hey @Datta-Telukunta Can you open a PR for the same?

**Comment by Datta-Telukunta** [comment]
Hey @prateek3255 , Pr link: https://github.com/devfolioco/react-otp-input/pull/419

**Comment by hogiyogi597** [comment]
Added a solution for this here: https://github.com/devfolioco/react-otp-input/pull/428

**Comment by prateek3255** [comment]
Was fixed with #428
