### ISSUE TITLE
In ios , i cant see value entered in otp box but same code works on android

### ISSUE THREAD

**Issue by shubham-khatod** [devfolioco/react-otp-input#421]
- **Describe the Feature Request**

- **Describe Preferred Solution**

**Comment by shubham-khatod** [comment]
<div style={{ marginTop: "20px" }} className="center">
                <OtpInput
                  inputStyle='otp-input-style'
                  value={this.state.otp}
                  onChange={this.handleChange}
                  numInputs={4}
                  isInputNum={true}
                  separator={<span>-</span>}
                  hasErrored={this.state.isIncorrectOtp}
                  errorStyle='otp-input-error'
                />
              </div>
![Simulator Screen Shot - iPhone 14 - 2023-09-30 at 11 18 44](https://github.com/devfolioco/react-otp-input/assets/123664838/531c6e02-77e8-460a-879d-9c8255679dff)

**Comment by shubham-khatod** [comment]
<div style={{ marginTop: "20px" }} className="center">
                <OtpInput
                  inputStyle='otp-input-style'
                  value={this.state.otp}
                  onChange={this.handleChange}
                  numInputs={4}
                  isInputNum={true}
                  separator={<span>-</span>}
                  hasErrored={this.state.isIncorrectOtp}
                  errorStyle='otp-input-error'
                />
              </div>

**Comment by prateek3255** [comment]
@shubham-khatod Can you upgrade to the latest version please, we don't have `errorStyle` etc. attributes anymore because the library no longer controls the input, you can add error styles directly to the input now
