### ISSUE TITLE
fix License 

### ISSUE THREAD

**Issue by Parikshit-Hooda** [devfolioco/react-otp-input#45]
- **Steps to reproduce the issue**:

- **Relevant error messages and/or screenshots**:
The license contains a line which says that the copyright is of year 2018 and I think this should be fixed to start from date of software inception to till the software/repo exists. A PR to include 2019 has been raised for now but this needs a permanent solution and hence, this issue.

**Comment by Parikshit-Hooda** [comment]
Please merge the PR beforehand as its opened as part of devfolioco hacktoberfest.

**Comment by Parikshit-Hooda** [comment]
@ajayns @kbardi

**Comment by kbardi** [comment]
I'm not an admin, I just made a fork, so I think I shouldn't update copyright

**Comment by apollonian** [comment]
I've updated the copyright now so going ahead to close the issue.
