### ISSUE TITLE
Demo site : Otp input boxes overflow and numInputs takes in negative values

### ISSUE THREAD

**Issue by robintom** [devfolioco/react-otp-input#47]
- **Steps to reproduce the issue**:

In the demo site , when the numInputs value is high the container overflows to sidebar. And the numInputs input box takes in negative values.

- **Relevant error messages and/or screenshots**:

![before-overflow](https://user-images.githubusercontent.com/31811117/66149646-27618800-e631-11e9-80c8-2c2ac3dfe128.png)

![numinputs-negativeValue](https://user-images.githubusercontent.com/31811117/66149664-2fb9c300-e631-11e9-8a1b-11699f6f02b9.png)

**Comment by robintom** [comment]
#46

**Comment by apollonian** [comment]
Fixed with PR #46
Thanks, @robintom!
