### ISSUE TITLE
Update License section in Readme file.

### ISSUE THREAD

**Issue by jddeep** [devfolioco/react-otp-input#61]
Update License section in Readme file.

- **Steps to reproduce the issue**:

Currently, under the 'License' section it is simply written MIT. This can be reformed into a correct structure for License showcasing like other substantial projects.

- **Relevant error messages and/or screenshots**:

Check the current Readme file.

**Comment by jddeep** [comment]
@apollonian @nashvail Can I work on this?

**Comment by apollonian** [comment]
@jddeep 🤔 I'm not exactly sure what you mean by correct structure in the README. We do have a LICENSE file in the repo and the same is accompanied with the release on npm.

**Comment by akashnimare** [comment]
@jddeep thanks for reporting this. I pushed a fix in https://github.com/devfolioco/react-otp-input/commit/449ab76c883111bf6656f86f9363a32d358fa85c.
