### ISSUE TITLE
Clear button is clearing the OTP even when isdisabled is activated.

### ISSUE THREAD

**Issue by saisrinivaspaila** [devfolioco/react-otp-input#64]
- **Describe the Feature Request**
When isdiabled is activated we cannot change any values to the OTP. But since the clear button is not disabled we can easily manipulate the OTP. So we need to disable the Clear button
- **Describe Preferred Solution**
I had made a New PR which disabled that button

**Comment by saisrinivaspaila** [comment]
**[Disable Clear if isDisable is activated](https://github.com/devfolioco/react-otp-input/pull/63)** clears the issue

**Comment by apollonian** [comment]
Merged the aforementioned PR, hence closing the issue.
Thanks again, @saisrinivaspaila.
✨
