### ISSUE TITLE
Make demo site responsive

### ISSUE THREAD

**Issue by AviKKi** [devfolioco/react-otp-input#69]
- **Describe the Feature Request**
Currently the website looks like this on mobile devices
![Screenshot_20191009-064150](https://user-images.githubusercontent.com/34864662/66444232-10230000-ea60-11e9-9e44-8ceceaac6369.png)

- **Describe Preferred Solution**
The left bar should appear on the top and otp component below it, on small devices.

I would love to work on it, assign it to me.

**Comment by Critchkn** [comment]
Hey there, 

I'd like to take a crack at this if it is available still

**Comment by apollonian** [comment]
Thanks for reporting it!
@AviKKi, @Critchkn The issue is now fixed with #88.
