### ISSUE TITLE
Clear inputs

### ISSUE THREAD

**Issue by Nikitakhanna92** [devfolioco/react-otp-input#7]
There should be a way to clear inputs as after resend I'm not able to clear inputs

**Comment by ajayns** [comment]
Agreed! Will be adding this feature soon but we'd also appreciate PRs :)

**Comment by ajayns** [comment]
This functionality to change the internal value of the OTP would require the whole component pattern to be changed from uncontrolled to controlled input pattern. Will have to do research on best implementation if we're trying to cause any breaking changes.

**Comment by KhamatdinovRT** [comment]
> This functionality to change the internal value of the OTP would require the whole component pattern to be changed from uncontrolled to controlled input pattern. Will have to do research on best implementation if we're trying to cause any breaking changes.

Will PR this feature soon

**Comment by KhamatdinovRT** [comment]
@ajayns I think `value` prop should be like `Array<string>`. And it could be passed to onChange handler same way `Array<string>`. It can be easily converted to string outside of component like value.join(''), for example. Are ok with such API?

**Comment by ajayns** [comment]
Apologies for the late reply. Developers just require the text/code in the input, it's a very rare scenario that they require the code split into an Array. Considering this and to keep the API/usage as simple as possible I'd recommend handling it as an Array internally while exposing just the string with the component API.

Also do note error handling would be required in the case `numInputs` and `value.length` don't match.

**Comment by Nikitakhanna92** [comment]
> There should be a way to clear inputs as after resend I'm not able to clear inputs

is there any update on this?

**Comment by wxqee** [comment]
Got a temporary solution here, just set props `key={renderTime}` and reset value by `this.setState({ renderTime: Date.now() })` can cause a new instance of OTP on UI. Wish some help.

> > There should be a way to clear inputs as after resend I'm not able to clear inputs
> 
> is there any update on this?

**Comment by ajayns** [comment]
Resolved with #23

**Comment by Nikitakhanna92** [comment]
to do this .... 
you can make a seperate component like this . and import   'react-otp-input' . use super.render to access the component props.This works ::::

import React, { Component } from 'react';
import Otp from 'react-otp-input';

class OtpComponent extends Otp{

    componentWillReceiveProps(nextProps){
       if(nextProps && this.props && nextProps.reset && this.props.reset!==nextProps.reset){
            this.setState({
                otp:["","","","","",""]
            })
        }
    }
    render(){
        return(super.render())
    }
}
