### ISSUE TITLE
Issues with isInputNum field enabled

### ISSUE THREAD

**Issue by vishalpolley** [devfolioco/react-otp-input#81]
- **Describe the Feature Request**
There are couple of issues coming up on enabling the `isInputNum` checkbox field -
  - `value` field accepting inputs other than number.
  - `otp` field accepting character values.
  - zero value is not accepted on `otp` field

- **Describe Preferred Solution**
  - The preferred solution for issues 1 and 2 is to restrict the values other than numbers as the `handeOnKeyDown` event is called.
  - The third issue can be solved if we change 
  ```onChange(isInputNum ? Number(otpValue) : otpValue)```  to
  ```onChange(otpValue)```
  inside the `handleOtpChange` function.

**Comment by devcer** [comment]
Hi, Can I take this up and work on this?

**Comment by vishalsureify** [comment]
> Hi, Can I take this up and work on this?

Hi @devcer the issue has been resolved in the PR #82 
Thanks!
