### ISSUE TITLE
Add custom prop for test tools/libraries able select react-otp-input inputs

### ISSUE THREAD

**Issue by aleksandrmaksimoviclt** [devfolioco/react-otp-input#96]
- **Describe the Feature Request**
Add custom prop for test tools/libraries able select react-otp-input component inputs
- **Describe Preferred Solution**
We write:
`<OtpInput numInputs={6} testProp="testprop-" />`
We then able to select inputs programatically in preferred test tools/libraries:
`testprop-1` - first input
`testprop-2` - second input
`testprop-3` - third input
`testprop-4` - fourth input
`testprop-5` - fifth input
`testprop-6` - sixth input

**Comment by sparkingdark** [comment]
can you tell elaborately like is it for testing purpose?

**Comment by afkatja** [comment]
+1 on this
To create a snapshot test, we need to add a custom prop `data-test-id` to the element. 
But this is just one scenario; actually, it would be nice to have support for other custom additional props.
